2025-10-16 21:25:06,608 1785269 ERROR metal-prod-18 odoo.addons.mindee_ai.models.account_move: [OCR][Runner][EXCEPTION] Expecting value: line 1 column 1 (char 0) 
2025-10-17 09:11:58,545 1909947 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 41, in call_button
    get_public_method(Model, method)
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 38, in get_public_method
    raise AttributeError(f"The method '{model._name}.{name}' does not exist")  # noqa: TRY004
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: The method 'account.move.action_ocr_fetch' does not exist
2025-10-17 09:15:38,404 1910762 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 41, in call_button
    get_public_method(Model, method)
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 38, in get_public_method
    raise AttributeError(f"The method '{model._name}.{name}' does not exist")  # noqa: TRY004
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: The method 'account.move.action_ocr_fetch' does not exist
2025-10-17 09:16:35,873 1910762 ERROR metal-prod-18 odoo.modules.registry: Failed to load registry 
2025-10-17 09:16:37,234 1910762 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 42, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_module.py", line 678, in button_immediate_upgrade
    return self._button_immediate_function(self.env.registry[self._name].button_upgrade)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_module.py", line 611, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 228, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 615, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 686, in convert_xml_import
    obj.parse(doc.getroot())
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 601, in parse
    self._tag_root(de)
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 555, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing /data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/views/account_move.xml:24
Erreur lors de la validation de la vue :

<form string="Account Entry" js_class="account_move_form" __validate__="1">
                    <header>
                        <!-- Post -->
                        <button name="action_post" string="Post" class="oe_highlight" type="object" groups="account.group_account_invoice" data-hotkey="q" context="{'validate_analytic': True, 'disable_abnormal_invoice_detection': False}" invisible="hide_post_button or move_type != 'entry'"/>
                        <button name="action_post" string="Confirm" class="oe_highlight" type="object" groups="account.group_account_invoice" data-hotkey="q" context="{'validate_analytic': True, 'disable_abnormal_invoice_detection': False}" invisible="hide_post_button or move_type == 'entry' or display_inactive_currency_warning"/>

action_ocr_fetch n'est pas une action valide sur account.move

View error context:
{'file': '/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/views/account_move.xml',
 'line': 3,
 'name': 'invoice.form.inherit.account.move',
 'view': ir.ui.view(3493,),
 'view.model': 'account.move',
 'view.parent': ir.ui.view(690,),
 'xmlid': 'view_move_form_inherit_ocr_button'}

2025-10-17 09:28:17,130 1912968 ERROR metal-prod-18 odoo.modules.registry: Failed to load registry 
2025-10-17 09:28:17,425 1912968 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 42, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_module.py", line 678, in button_immediate_upgrade
    return self._button_immediate_function(self.env.registry[self._name].button_upgrade)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_module.py", line 611, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 228, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 615, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 686, in convert_xml_import
    obj.parse(doc.getroot())
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 601, in parse
    self._tag_root(de)
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/convert.py", line 555, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing /data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/views/account_move.xml:24
Erreur lors de la validation de la vue :

<form string="Account Entry" js_class="account_move_form" __validate__="1">
                    <header>
                        <!-- Post -->
                        <button name="action_post" string="Post" class="oe_highlight" type="object" groups="account.group_account_invoice" data-hotkey="q" context="{'validate_analytic': True, 'disable_abnormal_invoice_detection': False}" invisible="hide_post_button or move_type != 'entry'"/>
                        <button name="action_post" string="Confirm" class="oe_highlight" type="object" groups="account.group_account_invoice" data-hotkey="q" context="{'validate_analytic': True, 'disable_abnormal_invoice_detection': False}" invisible="hide_post_button or move_type == 'entry' or display_inactive_currency_warning"/>

action_ocr_fetch n'est pas une action valide sur account.move

View error context:
{'file': '/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/views/account_move.xml',
 'line': 3,
 'name': 'invoice.form.inherit.account.move',
 'view': ir.ui.view(3493,),
 'view.model': 'account.move',
 'view.parent': ir.ui.view(690,),
 'xmlid': 'view_move_form_inherit_ocr_button'}

2025-10-17 09:59:41,809 1918936 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 42, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 240, in action_ocr_fetch
    price_unit = _to_float(pu_raw)
                 ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 237, in _to_float
    return float(val.replace(",", ".").replace(" ", ""))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'PrixUnitaire'
2025-10-17 17:55:30,022 2011243 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 42, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 247, in action_ocr_fetch
    if y not in rows:
                ^^^^
NameError: name 'rows' is not defined
2025-10-17 17:58:12,214 2012101 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 42, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 248, in action_ocr_fetch
    if y not in rows:
                ^^^^
NameError: name 'rows' is not defined
2025-10-17 18:01:19,236 2013019 CRITICAL metal-prod-18 odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:01:19,239 2013019 ERROR metal-prod-18 odoo.modules.registry: Failed to load registry 
2025-10-17 18:01:19,239 2013019 CRITICAL metal-prod-18 odoo.service.server: Failed to initialize database `metal-prod-18`. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/service/server.py", line 1361, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:01:33,604 2013019 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:01:33,606 2013019 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 18:01:33,606 2013019 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:01:43,396 2013019 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:01:43,398 2013019 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 18:01:43,398 2013019 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:02:35,037 2013019 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:02:35,039 2013019 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 18:02:35,039 2013019 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:02:44,721 2013019 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:02:44,723 2013019 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 18:02:44,724 2013019 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:03:36,287 2013019 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:03:36,289 2013019 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 18:03:36,289 2013019 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:03:45,850 2013019 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 18:03:45,852 2013019 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 18:03:45,852 2013019 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 251
    rows[y][z.get("label")] = (z.get("text") or "").strip()
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 250
2025-10-17 18:04:59,874 2013753 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 42, in call_button
    action = call_kw(request.env[model], method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 284, in action_ocr_fetch
    comment_lines.append(comment_text)
    ^^^^^^^^^^^^^
NameError: name 'comment_lines' is not defined
2025-10-17 19:02:03,376 2027275 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 41, in call_button
    get_public_method(Model, method)
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 38, in get_public_method
    raise AttributeError(f"The method '{model._name}.{name}' does not exist")  # noqa: TRY004
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: The method 'account.move.action_ocr_fetch' does not exist
2025-10-17 19:29:56,017 2033844 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 41, in call_button
    get_public_method(Model, method)
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 38, in get_public_method
    raise AttributeError(f"The method '{model._name}.{name}' does not exist")  # noqa: TRY004
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: The method 'account.move.action_ocr_fetch' does not exist
2025-10-17 19:31:57,957 2034348 ERROR metal-prod-18 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2081, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/addons/web/controllers/dataset.py", line 41, in call_button
    get_public_method(Model, method)
  File "/data/odoo/metal-odoo18-p8179/odoo/service/model.py", line 38, in get_public_method
    raise AttributeError(f"The method '{model._name}.{name}' does not exist")  # noqa: TRY004
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: The method 'account.move.action_ocr_fetch' does not exist
2025-10-17 19:43:52,454 2036970 CRITICAL metal-prod-18 odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:43:52,457 2036970 ERROR metal-prod-18 odoo.modules.registry: Failed to load registry 
2025-10-17 19:43:52,457 2036970 CRITICAL metal-prod-18 odoo.service.server: Failed to initialize database `metal-prod-18`. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/service/server.py", line 1361, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:19,480 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:19,482 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:19,482 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:21,884 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:21,886 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:21,887 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:25,518 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:25,520 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:25,520 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:29,310 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:29,312 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:29,312 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:30,180 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:30,182 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:30,183 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:30,275 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:30,277 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:30,277 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:30,890 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:30,892 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:30,892 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:32,845 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:32,848 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:32,848 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:39,340 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:39,342 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:39,342 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:44:52,230 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:44:52,232 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:44:52,232 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:45:11,713 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:45:11,715 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:45:11,715 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:45:30,283 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:45:30,285 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:45:30,285 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:45:30,980 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:45:30,982 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:45:30,982 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:45:40,971 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:45:40,973 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:45:40,973 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:46:25,377 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:46:25,379 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:46:25,380 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:46:31,999 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:46:32,001 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:46:32,001 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:47:31,625 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:47:31,627 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:47:31,627 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
2025-10-17 19:47:32,844 2036970 CRITICAL ? odoo.modules.module: Couldn't load module mindee_ai 
2025-10-17 19:47:32,846 2036970 ERROR ? odoo.modules.registry: Failed to load registry 
2025-10-17 19:47:32,847 2036970 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 106, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'metal-prod-18'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2554, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 2058, in _serve_db
    self.registry, cr_readwrite = self._open_registry()
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/http.py", line 1668, in _open_registry
    registry = Registry(self.db)
               ^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 108, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/data/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 485, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/data/odoo/metal-odoo18-p8179/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/__init__.py", line 2, in <module>
    from . import models
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/__init__.py", line 2, in <module>
    from . import account_move
  File "/data/odoo/metal-odoo18-p8179/myaddons/mindee_ai/models/account_move.py", line 242
    import base64
    ^^^^^^
SyntaxError: invalid syntax
